[package]
name = "simple_ocl_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.5"
ndarray = "0.16"
ocl = "0.19"
simple_ocl = { path = "../simple_ocl" }
