[package]
name = "simple_ocl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
ocl = "0.19.5"
simple_ocl_proc = { path = "../simple_ocl_proc" }
